<?php
/**
 * @var yii\web\View $this
 * @var app\models\RequestReserva $model
 * @var yii\widgets\ActiveForm $form
 */
?>


<!-- attribute fecha -->
<?php echo $form->field($model, 'fecha')->textInput() ?>

<!-- attribute desde -->
<?php echo $form->field($model, 'desde')->textInput() ?>

<!-- attribute hasta -->
<?php echo $form->field($model, 'hasta')->textInput() ?>

<!-- attribute denominacion -->
<?php echo $form->field($model, 'denominacion')->textInput(['maxlength' => true]) ?>

<!-- attribute email -->
<?php echo $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

<!-- attribute pax -->
<?php echo $form->field($model, 'pax')->textInput() ?>

<!-- attribute hash -->
<?php echo $form->field($model, 'hash')->textInput(['maxlength' => true]) ?>

<!-- attribute total -->
<?php echo $form->field($model, 'total')->textInput() ?>

<!-- attribute id_estado -->
<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_estado')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Estado::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_estado'])),
    ]
); ?>

<!-- attribute fecha_request_pago -->
<?php echo $form->field($model, 'fecha_request_pago')->textInput() ?>

<!-- attribute registro_pagos -->
<?php echo $form->field($model, 'registro_pagos')->textInput() ?>

<!-- attribute email_token -->
<?php echo $form->field($model, 'email_token')->textInput(['maxlength' => true]) ?>

<!-- attribute email_token_expira -->
<?php echo $form->field($model, 'email_token_expira')->textInput() ?>

<!-- attribute id_reserva -->
<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_reserva')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Reserva::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_reserva'])),
    ]
); ?>

<!-- attribute pagado -->
<?php echo $form->field($model, 'pagado')->textInput() ?>

<!-- attribute obs -->
<?php echo $form->field($model, 'obs')->textarea(['rows' => 6]) ?>