<?php
/**
 * @var yii\web\View $this
 * @var app\models\Notificaciones $model
 * @var yii\widgets\ActiveForm $form
 */
?>


<!-- attribute id_msg -->
<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_msg')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\NotifMensajes::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_msg'])),
    ]
); ?>

<!-- attribute id_user -->
<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_user')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Usuario::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_user'])),
    ]
); ?>

<!-- attribute leida -->
<?php echo $form->field($model, 'leida')->textInput() ?>