<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'El archivo ya fue descargado' => 'O arquivo já foi baixado',
    'El proceso de backup ha comenzado. Recibirás una notificación para descargarlo una vez esté listo' => 'O processo de backup foi iniciado. Você receberá uma notificação para baixá-lo quando estiver pronto',
    'El proceso de backup ya se encuentra en ejecución' => 'O processo de backup já está em execução',
    'Guardar' => 'Salvar',
    'Hola, {name}' => 'Olá, {name}',
    'Ingrese la contraseña' => 'Digite a senha',
    'La contraseña no puede estar vacia' => 'A senha não pode estar vazia',
    'La nueva contraseña se guardo exitosamente!' => 'A nova senha foi salva com sucesso!',
    'No podemos limpiar su contraseña con este email' => 'Não podemos redefinir sua senha com este e-mail',
    'Password reset token erroneo' => 'Token de redefinição de senha inválido',
    'Repita' => 'Repetir',
    'Se elimino correctamente' => 'Excluído com sucesso',
    'Se guardo correctamente' => 'Salvo com sucesso',
    'Siga el link de abajo para resetear su password:' => 'Siga o link abaixo para redefinir sua senha:',
    'Vea su correo y siga las instrucciones' => 'Verifique seu e-mail e siga as instruções',
    'no hay usuario con ese email' => 'Não há usuário com esse e-mail',
    'password' => 'senha',
    'repita la contraseña' => 'repita a senha',
];