<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' parametro' => 'parâmetro',
    'Acceso' => 'Acesso',
    'Access Token' => 'Token de Acesso',
    'Accion' => 'Ação',
    'Activar o desactivar el usuario' => 'Ativar ou desativar o usuário',
    'Activo' => 'Ativo',
    'Actualizar la base de datos' => 'Atualizar o banco de dados',
    'Actualizar la base de datos:' => 'Atualizar o banco de dados:',
    'Administrar Auditoria' => 'Gerenciar Auditoria',
    'Administrar Grupos de Acceso' => 'Gerenciar Grupos de Acesso',
    'Administrar Parametros Generales' => 'Gerenciar Parâmetros Gerais',
    'Administrar Usuarios' => 'Gerenciar Usuários',
    'Administrar notificaciones' => 'Gerenciar Notificações',
    'Apellido' => 'Sobrenome',
    'Auditoria' => 'Auditoria',
    'Auditoria Tabla' => 'Tabela de Auditoria',
    'Auditoria Tablas' => 'Tabelas de Auditoria',
    'Auditoria Ver' => 'Ver Auditoria',
    'Auditorias' => 'Auditorias',
    'Auth Key' => 'Chave de Autenticação',
    'Cambios' => 'Alterações',
    'Clave' => 'Chave',
    'Codigo' => 'Código',
    'Config' => 'Configuração',
    'Crear usuario' => 'Criar Usuário',
    'Created At' => 'Criado em',
    'Created By' => 'Criado por',
    'Descr' => 'Descrição',
    'Descripcion' => 'Descrição',
    'Deshacer la actualizacion en la base de datos:' => 'Desfazer atualização no banco de dados:',
    'Email' => 'E-mail',
    'Enabled' => 'Habilitado',
    'File' => 'Arquivo',
    'Generado' => 'Gerado',
    'Grupo Acceso' => 'Grupo de Acesso',
    'Grupos de Accesos' => 'Grupos de Acesso',
    'Grupos de acceso' => 'Grupos de Acesso',
    'ID' => 'ID',
    'Id Msg' => 'ID da Mensagem',
    'Id User' => 'ID do Usuário',
    'Indique el nivel de acceso' => 'Indique o nível de acesso',
    'Ingrese el Apellido del Usuario' => 'Informe o sobrenome do usuário',
    'Ingrese el Codigo del usuario' => 'Informe o código do usuário',
    'Ingrese el Nombre' => 'Informe o nome',
    'Ingrese el Nombre del Usuario' => 'Informe o nome do usuário',
    'Ingrese el usuario (login)' => 'Informe o usuário (login)',
    'Ingrese la contraseña del Usuario' => 'Informe a senha do usuário',
    'Ip origen' => 'IP de origem',
    'Jerarquia' => 'Hierarquia',
    'Label' => 'Rótulo',
    'Leida' => 'Lida',
    'Locate' => 'Localizar',
    'Menu' => 'Menu',
    'Menu Path' => 'Caminho do Menu',
    'Modificar Grupo de acceso' => 'Editar Grupo de Acesso',
    'Modificar Parametro General' => 'Editar Parâmetro Geral',
    'Modificar Usuario' => 'Editar Usuário',
    'Modificar:' => 'Modificar:',
    'Msg' => 'Mensagem',
    'Nombre' => 'Nome',
    'Notif Tablas' => 'Tabelas de Notificação',
    'Notificaciones' => 'Notificações',
    'Parametros Generales' => 'Parâmetros Gerais',
    'Password' => 'Senha',
    'Password Hash' => 'Hash da Senha',
    'Password Reset Token' => 'Token de Redefinição de Senha',
    'Pk ID' => 'ID Primário',
    'Rollback version en la base de datos' => 'Reverter versão no banco de dados',
    'Tabla' => 'Tabela',
    'Ultimo ingreso' => 'Último acesso',
    'Updated At' => 'Atualizado em',
    'Updated By' => 'Atualizado por',
    'Url' => 'URL',
    'User Sign Token' => 'Token de Assinatura do Usuário',
    'Usuario' => 'Usuário',
    'Usuarios' => 'Usuários',
    'Valor' => 'Valor',
    'Ver Grupo de acceso' => 'Ver Grupo de Acesso',
    'Ver Usuario' => 'Ver Usuário',
    'direccion de Email' => 'Endereço de e-mail',
    'id Accesos' => 'ID de Acesso',
    'id Grupo Acceso' => 'ID do Grupo de Acesso',
    'id Session' => 'ID da Sessão',
    'id Usuario' => 'ID do Usuário',
];