<?php
/**
 * @var yii\web\View $this
 * @var app\models\Reserva $model
 * @var yii\widgets\ActiveForm $form
 */
?>


<!-- attribute fecha -->
<?php echo $form->field($model, 'fecha')->textInput() ?>

<!-- attribute desde -->
<?php echo $form->field($model, 'desde')->textInput() ?>

<!-- attribute hasta -->
<?php echo $form->field($model, 'hasta')->textInput() ?>

<!-- attribute id_locador -->
<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_locador')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Locador::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_locador'])),
    ]
); ?>

<!-- attribute pax -->
<?php echo $form->field($model, 'pax')->textInput() ?>

<!-- attribute id_estado -->
<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_estado')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Estado::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_estado'])),
    ]
); ?>

<!-- attribute obs -->
<?php echo $form->field($model, 'obs')->textarea(['rows' => 6]) ?>