<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Reserva $model
*/

$this->title = Yii::t('models', 'Reserva');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models.plural', 'Reserva'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud reserva-view">

    <h1>
        <?= Html::encode($model->id) ?>
        <small><?= Yii::t('cruds', 'Reserva') ?></small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>

                        <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('cruds', 'Edit Reserva'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info'])
            ?>
            
                                    <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('cruds', 'Copy Reserva'),
            ['create', 'id' => $model->id, 'Reserva'=> $model->hasMethod('getCopyParams') ? $model->getCopyParams() : $model->attributes],
            ['class' => 'btn btn-success'])
            ?>
                        
                        <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New Reserva'),
            ['create'],
            ['class' => 'btn btn-success'])
            ?>
                    </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('cruds', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\Reserva'); ?>

    
    <?php 
 echo DetailView::widget([
    'model' => $model,
    'attributes' => [
            'fecha',
        'desde',
        'hasta',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'id_locador',
    'value' => ($model->locador ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['locador/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->locador->id, ['locador/view', 'id' => $model->locador->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Reserva'=>['id_locador' => $model->id_locador]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'pax',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'id_estado',
    'value' => ($model->estado ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['estado/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->estado->id, ['estado/view', 'id' => $model->estado->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Reserva'=>['id_estado' => $model->id_estado]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'obs:ntext',
    ],
    ]);
    ?>

    
    <hr/>

        <?php 
 echo Html::a('<span class="glyphicon glyphicon-trash"></span> '
    . Yii::t('cruds', 'Delete Reserva'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('cruds', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]);
    ?>
        <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('Cabanas'); ?>
<div style='float:right;'>
  <?php
        echo Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'List All Cabanas'),
            ['cabana/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New Cabanas'),
             ['cabana/create'],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-link"></span> ' . Yii::t('cruds', 'Attach Cabanas'), ['cabana/create', 'ReservaCabanas'=>['id'=>$model->id]],
            ['class'=>'btn btn-info btn-xs']
        ) ?>
</div>
<div class='clearfix'></div><?php Pjax::begin(['id'=>'pjax-Cabanas', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Cabanas ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getCabanas(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-cabanas',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::class,
        'firstPageLabel' => Yii::t('cruds', 'First'),
        'lastPageLabel'  => Yii::t('cruds', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'cabana' . '/' . $action;
        $params['Cabana'] = ['id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'cabana'
],
        'id',
        'descr',
        'checkin',
        'checkout',
        'max_pax',
        'activa',
        'caracteristicas',
        'created_at',
        'created_by',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('RequestReservas'); ?>
<div style='float:right;'>
  <?php
        echo Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'List All Request Reservas'),
            ['request-reserva/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New Request Reservas'),
             ['request-reserva/create', 'RequestReserva' => ['id_reserva' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
<div class='clearfix'></div><?php Pjax::begin(['id'=>'pjax-RequestReservas', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-RequestReservas ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getRequestReservas(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-requestreservas',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::class,
        'firstPageLabel' => Yii::t('cruds', 'First'),
        'lastPageLabel'  => Yii::t('cruds', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'request-reserva' . '/' . $action;
        $params['RequestReserva'] = ['id_reserva' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'request-reserva'
],
        'id',
        'fecha',
        'desde',
        'hasta',
        'denominacion',
        'email:email',
        'pax',
        'hash',
        'total',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('ReservaCabanas'); ?>
<div style='float:right;'>
  <?php
        echo Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'List All Reserva Cabanas'),
            ['reserva-cabana/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New Reserva Cabanas'),
             ['reserva-cabana/create', 'ReservaCabana' => ['id_reserva' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
<div class='clearfix'></div><?php Pjax::begin(['id'=>'pjax-ReservaCabanas', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-ReservaCabanas ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getReservaCabanas(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-reservacabanas',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::class,
        'firstPageLabel' => Yii::t('cruds', 'First'),
        'lastPageLabel'  => Yii::t('cruds', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'reserva-cabana' . '/' . $action;
        $params['ReservaCabana'] = ['id_reserva' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'reserva-cabana'
],
        'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::class,
    'attribute' => 'id_cabana',
    'value' => function ($model) {
        if ($rel = $model->cabana) {
            return Html::a($rel->id, ['cabana/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::class,
    'attribute' => 'id_reserva',
    'value' => function ($model) {
        if ($rel = $model->reserva) {
            return Html::a($rel->id, ['reserva/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'valor',
        'created_at',
        'created_by',
        'updated_at',
        'updated_by',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?php 
        echo Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b>' . \Yii::t('cruds', '# {primaryKey}', ['primaryKey' => Html::encode($model->id)]) . '</b>',
    'content' => $this->blocks['app\models\Reserva'],
    'active'  => true,
],
[
    'content' => $this->blocks['Cabanas'],
    'label'   => '<small>' . Yii::t('cruds', 'Cabanas') .' <span class="badge badge-default">'. $model->getCabanas()->count() . '</span></small>',
    'active'  => false,
],
[
    'content' => $this->blocks['RequestReservas'],
    'label'   => '<small>' . Yii::t('cruds', 'Request Reservas') .' <span class="badge badge-default">'. $model->getRequestReservas()->count() . '</span></small>',
    'active'  => false,
],
[
    'content' => $this->blocks['ReservaCabanas'],
    'label'   => '<small>' . Yii::t('cruds', 'Reserva Cabanas') .' <span class="badge badge-default">'. $model->getReservaCabanas()->count() . '</span></small>',
    'active'  => false,
],
 ]
                 ]
    );
    ?>
</div>
