<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'El archivo ya fue descargado' => 'The file has already been downloaded',
    'El proceso de backup ha comenzado. Recibirás una notificación para descargarlo una vez esté listo' => 'The backup process has started. You will receive a notification to download it once it is ready',
    'El proceso de backup ya se encuentra en ejecución' => 'The backup process is already running',
    'Guardar' => 'Save',
    'Hola, {name}' => 'Hello, {name}',
    'Ingrese la contraseña' => 'Enter the password',
    'La contraseña no puede estar vacia' => 'The password cannot be empty',
    'La nueva contraseña se guardo exitosamente!' => 'The new password was saved successfully!',
    'No podemos limpiar su contraseña con este email' => 'We cannot reset your password with this email',
    'Password reset token erroneo' => 'Invalid password reset token',
    'Repita' => 'Repeat',
    'Se elimino correctamente' => 'Deleted successfully',
    'Se guardo correctamente' => 'Saved successfully',
    'Siga el link de abajo para resetear su password:' => 'Follow the link below to reset your password:',
    'Vea su correo y siga las instrucciones' => 'Check your email and follow the instructions',
    'no hay usuario con ese email' => 'There is no user with that email',
    'password' => 'password',
    'repita la contraseña' => 'repeat the password',
];