<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' parametro' => 'parameter',
    'Acceso' => 'Access',
    'Access Token' => 'Access Token',
    'Accion' => 'Action',
    'Activar o desactivar el usuario' => 'Activate or deactivate the user',
    'Activo' => 'Active',
    'Actualizar la base de datos' => 'Update the database',
    'Actualizar la base de datos:' => 'Update the database:',
    'Administrar Auditoria' => 'Manage Audit',
    'Administrar Grupos de Acceso' => 'Manage Access Groups',
    'Administrar Parametros Generales' => 'Manage General Parameters',
    'Administrar Usuarios' => 'Manage Users',
    'Administrar notificaciones' => 'Manage Notifications',
    'Apellido' => 'Last Name',
    'Auditoria' => 'Audit',
    'Auditoria Tabla' => 'Audit Table',
    'Auditoria Tablas' => 'Audit Tables',
    'Auditoria Ver' => 'View Audit',
    'Auditorias' => 'Audits',
    'Auth Key' => 'Auth Key',
    'Cambios' => 'Changes',
    'Clave' => 'Key',
    'Codigo' => 'Code',
    'Config' => 'Config',
    'Crear usuario' => 'Create User',
    'Created At' => 'Created At',
    'Created By' => 'Created By',
    'Descr' => 'Description',
    'Descripcion' => 'Description',
    'Deshacer la actualizacion en la base de datos:' => 'Undo database update:',
    'Email' => 'Email',
    'Enabled' => 'Enabled',
    'File' => 'File',
    'Generado' => 'Generated',
    'Grupo Acceso' => 'Access Group',
    'Grupos de Accesos' => 'Access Groups',
    'Grupos de acceso' => 'Access Groups',
    'ID' => 'ID',
    'Id Msg' => 'Message ID',
    'Id User' => 'User ID',
    'Indique el nivel de acceso' => 'Indicate the access level',
    'Ingrese el Apellido del Usuario' => 'Enter the user’s last name',
    'Ingrese el Codigo del usuario' => 'Enter the user code',
    'Ingrese el Nombre' => 'Enter the name',
    'Ingrese el Nombre del Usuario' => 'Enter the user’s name',
    'Ingrese el usuario (login)' => 'Enter the username (login)',
    'Ingrese la contraseña del Usuario' => 'Enter the user’s password',
    'Ip origen' => 'Source IP',
    'Jerarquia' => 'Hierarchy',
    'Label' => 'Label',
    'Leida' => 'Read',
    'Locate' => 'Locate',
    'Menu' => 'Menu',
    'Menu Path' => 'Menu Path',
    'Modificar Grupo de acceso' => 'Edit Access Group',
    'Modificar Parametro General' => 'Edit General Parameter',
    'Modificar Usuario' => 'Edit User',
    'Modificar:' => 'Modify:',
    'Msg' => 'Message',
    'Nombre' => 'Name',
    'Notif Tablas' => 'Notification Tables',
    'Notificaciones' => 'Notifications',
    'Parametros Generales' => 'General Parameters',
    'Password' => 'Password',
    'Password Hash' => 'Password Hash',
    'Password Reset Token' => 'Password Reset Token',
    'Pk ID' => 'Primary Key ID',
    'Rollback version en la base de datos' => 'Rollback database version',
    'Tabla' => 'Table',
    'Ultimo ingreso' => 'Last Login',
    'Updated At' => 'Updated At',
    'Updated By' => 'Updated By',
    'Url' => 'URL',
    'User Sign Token' => 'User Sign Token',
    'Usuario' => 'User',
    'Usuarios' => 'Users',
    'Valor' => 'Value',
    'Ver Grupo de acceso' => 'View Access Group',
    'Ver Usuario' => 'View User',
    'direccion de Email' => 'Email address',
    'id Accesos' => 'Access ID',
    'id Grupo Acceso' => 'Access Group ID',
    'id Session' => 'Session ID',
    'id Usuario' => 'User ID',
];