<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\controllers\base;

use app\models\Usuario;
use app\models\UsuarioSearch;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\base\InvalidConfigException;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Request;
use yii\web\Response;
use Yii;

/**
 * UsuarioController implements the CRUD actions for Usuario model.
 *
 * @property-read Request $request
 */
class UsuarioController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::class,
                    'rules' => [
                        [
                            'allow' => true,
                            'actions' => ['index', 'view', 'create', 'update', 'delete'],
                            'roles' => ['?', '@'],
                        ],
                        [
                            'allow' => true,
                            'actions' => ['index', 'view'],
                            'roles' => ['?', '@']
                        ],
                        [
                            'allow' => true,
                            'actions' => ['update', 'create', 'delete'],
                            'roles' => ['?', '@']
                        ],
                    ]
                ]
            ]
        );
    }

    /**
     * Lists all Usuario models.
     *
     * @throws InvalidConfigException
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(UsuarioSearch::class);
        $dataProvider = $searchModel->search($this->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Usuario model.
     *
     * @param integer $Id
     *
     * @throws NotFoundHttpException
     * @return string
     */
    public function actionView($Id)
    {
        return $this->render('view', ['model' => $this->findModel($Id)]);

    }

    /**
     * Creates a new Usuario model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @throws yii\base\InvalidConfigException
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = Yii::createObject(Usuario::class);
        try {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'Id' => $model->id]);
            }
            if (!Yii::$app->request->isPost) {
                $model->load($this->request->get());
            }
        } catch (\Exception $e) {
            $model->addError('_exception', $e->errorInfo[2] ?? $e->getMessage());
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Usuario model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $Id
     *
     * @throws NotFoundHttpException
     * @return string|Response
     */
    public function actionUpdate($Id)
    {
        $model = $this->findModel($Id);
        if ($model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'Id' => $model->Id]);
        }
        return $this->render('update', ['model' => $model]);
    }

    /**
     * Deletes an existing Usuario model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $Id
     *
     * @throws \Throwable
     * @return Response
     */
    public function actionDelete($Id)
    {
        try {
            $this->findModel($Id)->delete();
        } catch (\Exception $e) {
            Yii::$app->getSession()->addFlash('error', $e->errorInfo[2] ?? $e->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Usuario model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @throws NotFoundHttpException if the model cannot be found
     * @return Usuario the loaded model
     */
    protected function findModel($id)
    {
        $model = Usuario::findOne($id);
        if ($model !== null) {
            return $model;
        }
        throw new NotFoundHttpException(Yii::t('cruds', 'The requested page does not exist.'));
    }
}
