<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "acceso".
 *
 * @property integer $id
 * @property string $descr
 * @property string $acceso
 * @property array $config
 * @property integer $id_menu
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\GrupoAcceso[] $grupoAccesos
 * @property \app\models\GrupoAccesoAcceso[] $gruposAccesosAccesos
 * @property \app\models\Menu $menu
 * @property \app\models\Usuario[] $usuarios
 * @property \app\models\UsuarioAcceso[] $usuariosAccesos
 */
abstract class Acceso extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'acceso';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['descr', 'acceso'], 'required'],
            [['config'], 'safe'],
            [['id_menu'], 'integer'],
            [['descr', 'acceso'], 'string', 'max' => 80],
            [['acceso'], 'unique'],
            [['id_menu'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Menu::class, 'targetAttribute' => ['id_menu' => 'id']]            
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'descr' => Yii::t('models', 'Descr'),
            'acceso' => Yii::t('models', 'Acceso'),
            'config' => Yii::t('models', 'Config'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_by' => Yii::t('models', 'Updated By'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'id_menu' => Yii::t('models', 'Menu'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrupoAccesos()
    {
        return $this->hasMany(\app\models\GrupoAcceso::class, ['id' => 'id_grupo_acceso'])->viaTable('grupos_accesos_accesos', ['id_acceso' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenu()
    {
        return $this->hasOne(\app\models\Menu::class, ['id' => 'id_menu']);
    }    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGruposAccesosAccesos()
    {
        return $this->hasMany(\app\models\GrupoAccesoAcceso::class, ['id_acceso' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuarios()
    {
        return $this->hasMany(\app\models\Usuario::class, ['id' => 'id_usuario'])->viaTable('usuarios_accesos', ['id_accesos' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuariosAccesos()
    {
        return $this->hasMany(\app\models\UsuarioAcceso::class, ['id_accesos' => 'id']);
    }

}
