<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "auditorias".
 *
 * @property integer $id
 * @property string $tabla
 * @property array $changes
 * @property string $user
 * @property string $action
 * @property array $pkId
 * @property string $created_at
 * @property integer $updated_at
 */
abstract class Auditoria extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'auditorias';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['tabla', 'changes', 'user', 'action', 'pkId'], 'required'],
            [['changes', 'pkId'], 'safe'],
            [['tabla', 'user', 'action'], 'string', 'max' => 45]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'tabla' => Yii::t('models', 'Tabla'),
            'changes' => Yii::t('models', 'Cambios'),
            'user' => Yii::t('models', 'Usuario'),
            'action' => Yii::t('models', 'Accion'),
            'pkId' => Yii::t('models', 'Pk ID'),
            'created_at' => Yii::t('models', 'Generado'),
            'updated_at' => Yii::t('models', 'Updated At'),
        ]);
    }

}
