<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "grupo_acceso".
 *
 * @property integer $id
 * @property string $descr
 * @property integer $nivel
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Acceso[] $accesos
 * @property \app\models\GrupoAccesoAcceso[] $gruposAccesosAccesos
 * @property \app\models\GrupoAccesoUsuario[] $gruposAccesosUsuarios
 * @property \app\models\Usuario[] $usuarios
 */
abstract class GrupoAcceso extends ActiveRecordAudit
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'grupo_acceso';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['descr','nivel'], 'required'],
            [['nivel'], 'integer', 'min' => 0, 'max' => 5],
            [['descr'], 'string', 'max' => 45],
            [['descr'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'descr' => Yii::t('models', 'Nombre'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_by' => Yii::t('models', 'Updated By'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'nivel' => Yii::t('models', 'Jerarquia'),
        ]);
    }


    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'id' => Yii::t('models', 'ID'),
            'descr' => Yii::t('models', 'Ingrese el Nombre'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_by' => Yii::t('models', 'Updated By'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'nivel' => Yii::t('models', 'Indique el nivel de acceso'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccesos()
    {
        return $this->hasMany(\app\models\Acceso::class, ['id' => 'id_acceso'])->viaTable('grupos_accesos_accesos', ['id_grupo_acceso' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGruposAccesosAccesos()
    {
        return $this->hasMany(\app\models\GrupoAccesoAcceso::class, ['id_grupo_acceso' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGruposAccesosUsuarios()
    {
        return $this->hasMany(\app\models\GrupoAccesoUsuario::class, ['id_grupo_acceso' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuarios()
    {
        return $this->hasMany(\app\models\Usuario::class, ['id' => 'id_usuario'])->viaTable('grupos_accesos_usuarios', ['id_grupo_acceso' => 'id']);
    }

}
