<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "grupos_accesos_accesos".
 *
 * @property integer $id_grupo_acceso
 * @property integer $id_acceso
 *
 * @property \app\models\Acceso $accesos
 * @property \app\models\GrupoAcceso $grupoAcceso
 */
abstract class GrupoAccesoAcceso extends ActiveRecordAudit
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'grupos_accesos_accesos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['id_grupo_acceso', 'id_acceso'], 'required'],
            [['id_grupo_acceso', 'id_acceso'], 'integer'],
            [['id_grupo_acceso', 'id_acceso'], 'unique', 'targetAttribute' => ['id_grupo_acceso', 'id_acceso']],
            [['id_acceso'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Acceso::class, 'targetAttribute' => ['id_acceso' => 'id']],
            [['id_grupo_acceso'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\GrupoAcceso::class, 'targetAttribute' => ['id_grupo_acceso' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id_grupo_acceso' => Yii::t('models', 'id Grupo Acceso'),
            'id_acceso' => Yii::t('models', 'id Accesos'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccesos()
    {
        return $this->hasOne(\app\models\Acceso::class, ['id' => 'id_acceso']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrupoAcceso()
    {
        return $this->hasOne(\app\models\GrupoAcceso::class, ['id' => 'id_grupo_acceso']);
    }

}
