<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "menu".
 *
 * @property integer $id
 * @property string $descr
 * @property string $label
 * @property string $menu
 * @property string $menu_path
 * @property string $url
 *
 * @property \app\models\Acceso[] $accesos
 */
abstract class Menu extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['descr', 'label', 'menu', 'menu_path', 'url'], 'required'],
            [['descr', 'menu_path'], 'string', 'max' => 85],
            [['label', 'menu'], 'string', 'max' => 45],
            [['url'], 'string', 'max' => 100],
            [['menu', 'menu_path'], 'unique', 'targetAttribute' => ['menu', 'menu_path']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'descr' => Yii::t('models', 'Descr'),
            'label' => Yii::t('models', 'Label'),
            'menu' => Yii::t('models', 'Menu'),
            'menu_path' => Yii::t('models', 'Menu Path'),
            'url' => Yii::t('models', 'Url'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccesos()
    {
        return $this->hasMany(\app\models\Acceso::class, ['id_menu' => 'id']);
    }

}
