<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "notificaciones".
 *
 * @property integer $id
 * @property integer $id_msg
 * @property integer $id_user
 * @property integer $leida
 * @property string $tabla
 *
 * @property \app\models\NotifMensajes $msg
 * @property \app\models\Usuario $user
 */
abstract class Notificaciones extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notificaciones';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['id_msg', 'id_user'], 'required'],
            [['id_msg', 'id_user', 'leida'], 'integer'],
            [['tabla'], 'string', 'max' => 45],
            [['id_msg'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\NotifMensajes::class, 'targetAttribute' => ['id_msg' => 'id']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Usuario::class, 'targetAttribute' => ['id_user' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'id_msg' => Yii::t('models', 'Id Msg'),
            'id_user' => Yii::t('models', 'Id User'),
            'leida' => Yii::t('models', 'Leida'),
            'tabla' => Yii::t('models', 'Tabla'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMsg()
    {
        return $this->hasOne(\app\models\NotifMensajes::class, ['id' => 'id_msg']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\Usuario::class, ['id' => 'id_user']);
    }

}
