<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "parametros_generales".
 *
 * @property integer $id
 * @property string $clave
 * @property string $descr
 * @property string $valor
 */
abstract class ParametrosGenerales extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'parametros_generales';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['clave', 'descr', 'valor'], 'required'],
            [['valor'], 'string'],
            [['clave'], 'string', 'max' => 30],
            [['descr'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'clave' => Yii::t('models', 'Clave'),
            'descr' => Yii::t('models', 'Descr'),
            'valor' => Yii::t('models', 'Valor'),
        ]);
    }

}
