<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "parametros_generales".
 *
 * @property integer $id
 * @property string $clave
 * @property string $descr
 * @property array $valor
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 */
abstract class ParametrosGenerales extends ActiveRecordAudit
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'parametros_generales';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['clave', 'valor','descr'], 'required'],
            [['valor'], 'safe'],
            [['clave'], 'string', 'max' => 45],
            [['descr'], 'string', 'max' => 255],
            [['clave'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'clave' => Yii::t('models', 'Clave'),
            'descr' => Yii::t('models', 'Descripcion'),
            'valor' => Yii::t('models', 'Valor'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

}
