<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;


/**
 * This is the base-model class for table "usuarios_accesos".
 *
 * @property integer $id_usuario
 * @property integer $id_accesos
 * @property string $created_at 
 * @property integer $created_by 
 * @property string $updated_at 
 * @property integer $updated_by 

 *
 * @property \app\models\Acceso $accesos
 * @property \app\models\Usuario $usuario
 */
abstract class UsuarioAcceso extends ActiveRecordAudit
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usuarios_accesos';
    }

  /** 
    * @inheritdoc 
    */ 
    public function behaviors() 
    { 
        $behaviors = parent::behaviors(); 
        $behaviors['blameable'] = [ 
            'class' => BlameableBehavior::class, 
        ]; 
        $behaviors['timestamp'] = [ 
            'class' => TimestampBehavior::class, 
            'value' => (new \DateTime())->format('Y-m-d H:i:s'), 
                        ]; 
         
    return $behaviors; 
    }
 



    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['id_usuario', 'id_accesos'], 'required'],
            [['id_usuario', 'id_accesos'], 'integer'],
            [['id_usuario', 'id_accesos'], 'unique', 'targetAttribute' => ['id_usuario', 'id_accesos']],
            [['id_accesos'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Acceso::class, 'targetAttribute' => ['id_accesos' => 'id']],
            [['id_usuario'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Usuario::class, 'targetAttribute' => ['id_usuario' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id_usuario' => Yii::t('models', 'id Usuario'),
            'id_accesos' => Yii::t('models', 'id Accesos'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),            
           
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccesos()
    {
        return $this->hasOne(\app\models\Acceso::class, ['id' => 'id_accesos']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuario()
    {
        return $this->hasOne(\app\models\Usuario::class, ['id' => 'id_usuario']);
    }

}
