<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Notificaciones $model
*/

$this->title = Yii::t('models', 'Notificaciones');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models.plural', 'Notificaciones'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud notificaciones-view">

    <h1>
        <?= Html::encode($model->id) ?>
        <small><?= Yii::t('cruds', 'Notificaciones') ?></small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>

            <?php if(\Yii::$app->getUser()->can('app_notificaciones_update')): ?>            <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('cruds', 'Edit Notificaciones'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info'])
            ?>
            <?php endif ?>
                        <?php if(\Yii::$app->getUser()->can('app_notificaciones_update')): ?>            <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('cruds', 'Copy Notificaciones'),
            ['create', 'id' => $model->id, 'Notificaciones'=> $model->hasMethod('getCopyParams') ? $model->getCopyParams() : $model->attributes],
            ['class' => 'btn btn-success'])
            ?>
            <?php endif ?>            
            <?php if(\Yii::$app->getUser()->can('app_notificaciones_create')): ?>            <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New Notificaciones'),
            ['create'],
            ['class' => 'btn btn-success'])
            ?>
            <?php endif ?>        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('cruds', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\Notificaciones'); ?>

    
    <?php 
 echo DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'id_msg',
    'value' => ($model->msg ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['notif-mensajes/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->msg->id, ['notif-mensajes/view', 'id' => $model->msg->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Notificaciones'=>['id_msg' => $model->id_msg]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'id_user',
    'value' => ($model->user ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['usuario/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->user->id, ['usuario/view', 'id' => $model->user->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Notificaciones'=>['id_user' => $model->id_user]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'leida',
    ],
    ]);
    ?>

    
    <hr/>

    <?php if(\Yii::$app->getUser()->can('app_notificaciones_delete')): ?>    <?php 
 echo Html::a('<span class="glyphicon glyphicon-trash"></span> '
    . Yii::t('cruds', 'Delete Notificaciones'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('cruds', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]);
    ?>
    <?php endif ?>    <?php $this->endBlock(); ?>


    
    <?php 
        echo Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b>' . \Yii::t('cruds', '# {primaryKey}', ['primaryKey' => Html::encode($model->id)]) . '</b>',
    'content' => $this->blocks['app\models\Notificaciones'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
