<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'El archivo ya fue descargado' => '',
    'El proceso de backup ha comenzado. Recibirás una notificación para descargarlo una vez esté listo' => '',
    'El proceso de backup ya se encuentra en ejecución' => '',
    'Guardar' => '@@Guardar@@',
    'Hola, {name}' => '@@Hola, {name}@@',
    'Ingrese la contraseña' => '',
    'La contraseña no puede estar vacia' => '',
    'La nueva contraseña se guardo exitosamente!' => '',
    'No podemos limpiar su contraseña con este email' => '',
    'Password reset token erroneo' => '',
    'Repita' => '',
    'Se elimino correctamente' => '',
    'Se guardo correctamente' => '',
    'Siga el link de abajo para resetear su password:' => '',
    'Vea su correo y siga las instrucciones' => '',
    'no hay usuario con ese email' => '',
    'password' => '',
    'repita la contraseña' => '',
];
