<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' parametro' => '',
    'Acceso' => '',
    'Access Token' => '',
    'Accion' => '',
    'Activar o desactivar el usuario' => '',
    'Activo' => '',
    'Actualizar la base de datos' => '',
    'Actualizar la base de datos:' => '',
    'Administrar Auditoria' => '',
    'Administrar Grupos de Acceso' => '',
    'Administrar Parametros Generales' => '',
    'Administrar Usuarios' => '',
    'Administrar notificaciones' => '',
    'Apellido' => '',
    'Auditoria' => '',
    'Auditoria Tabla' => '',
    'Auditoria Tablas' => '',
    'Auditoria Ver' => '',
    'Auditorias' => '',
    'Auth Key' => '',
    'Cambios' => '',
    'Clave' => '',
    'Codigo' => '',
    'Config' => '',
    'Crear usuario' => '',
    'Created At' => '',
    'Created By' => '',
    'Descr' => '',
    'Descripcion' => '',
    'Deshacer la actualizacion en la base de datos:' => '',
    'Email' => '',
    'Enabled' => '',
    'File' => '',
    'Generado' => '',
    'Grupo Acceso' => '',
    'Grupos de Accesos' => '',
    'Grupos de acceso' => '',
    'ID' => '',
    'Id Msg' => '',
    'Id User' => '',
    'Indique el nivel de acceso' => '',
    'Ingrese el Apellido del Usuario' => '',
    'Ingrese el Codigo del usuario' => '',
    'Ingrese el Nombre' => '',
    'Ingrese el Nombre del Usuario' => '',
    'Ingrese el usuario (login)' => '',
    'Ingrese la contraseña del Usuario' => '',
    'Ip origen' => '',
    'Jerarquia' => '',
    'Label' => '',
    'Leida' => '',
    'Locate' => '',
    'Menu' => '',
    'Menu Path' => '',
    'Modificar Grupo de acceso' => '',
    'Modificar Parametro General' => '',
    'Modificar Usuario' => '',
    'Modificar:' => '',
    'Msg' => '',
    'Nombre' => '',
    'Notif Tablas' => '',
    'Notificaciones' => '',
    'Parametros Generales' => '',
    'Password' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Pk ID' => '',
    'Rollback version en la base de datos' => '',
    'Tabla' => '',
    'Ultimo ingreso' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Url' => '',
    'User Sign Token' => '',
    'Usuario' => '',
    'Usuarios' => '',
    'Valor' => '',
    'Ver Grupo de acceso' => '',
    'Ver Usuario' => '',
    'direccion de Email' => '',
    'id Accesos' => '',
    'id Grupo Acceso' => '',
    'id Session' => '',
    'id Usuario' => '',
];
