<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "cabanas_tarifas".
 *
 * @property integer $id
 * @property integer $id_cabana
 * @property integer $id_tarifa
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Cabana $cabana
 * @property \app\models\Tarifa $tarifa
 */
abstract class CabanaTarifa extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cabanas_tarifas';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['id_cabana', 'id_tarifa'], 'required'],
            [['id_cabana', 'id_tarifa'], 'integer'],
            [['id_cabana', 'id_tarifa'], 'unique', 'targetAttribute' => ['id_cabana', 'id_tarifa']],
            [['id_cabana'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Cabana::class, 'targetAttribute' => ['id_cabana' => 'id']],
            [['id_tarifa'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Tarifa::class, 'targetAttribute' => ['id_tarifa' => 'id']],
            // 👇 validador de NO superposición
            [['id_tarifa'], 'validateTarifaRangeNoOverlap'],
        ]);
    }


    /**
     * Evita superponer rangos de tarifas para la misma cabaña.
     * Considera superposición cuando el rango nuevo toca o intersecta otro
     * (es decir, sólo NO se superpone si new_fin < old_inicio OR new_inicio > old_fin).
     */
    public function validateTarifaRangeNoOverlap($attribute, $params = [])
    {

        if (!$this->id_cabana || !$this->id_tarifa) {
            return;
        }

        /*
        $res = self::isTarifaRangeOverlap($this->id_cabana, $this->id_tarifa);

        if ($res['status'] == 'error') {
            $this->addError($attribute, $res['msg']);
            return;
        }


        if ($res['status'] == 'SI') {
            $this->addError($attribute, $res['msg']);
        }

        */

        

        /*
        if (!$this->id_cabana || !$this->id_tarifa) {
            return;
        }

        // Obtener la tarifa seleccionada y su rango
        $tarifa = \app\models\Tarifa::findOne($this->id_tarifa);
        if (!$tarifa || empty($tarifa->inicio) || empty($tarifa->fin)) {
            $this->addError($attribute, Yii::t('models', 'La tarifa seleccionada no tiene un rango válido.'));
            return;
        }

        $newInicio = $tarifa->inicio; // asume 'Y-m-d' o 'Y-m-d H:i:s' según tu BD
        $newFin = $tarifa->fin;

        // Si guardás como DATE y querés cubrir el día completo, podés ajustar:
        // if (strlen($newInicio) === 10) $newInicio .= ' 00:00:00';
        // if (strlen($newFin)    === 10) $newFin    .= ' 23:59:59';

        // Buscar cualquier vínculo existente de la misma cabaña cuyo rango se superponga
        $params = [
            ':cabana' => $this->id_cabana,
            ':new_inicio' => $newInicio,
            ':new_fin' => $newFin,
        ];

        $sql = "
                SELECT 1
                FROM cabanas_tarifas ct
                INNER JOIN tarifas t ON t.id = ct.id_tarifa
                WHERE ct.id_cabana = :cabana
                " . ($this->isNewRecord ? "" : "AND ct.id <> :self_id") . "
                AND NOT (
                        :new_fin   < t.inicio
                    OR  :new_inicio > t.fin
                )
                LIMIT 1
            ";

        if (!$this->isNewRecord) {
            $params[':self_id'] = $this->id;
        }

        $exists = (new \yii\db\Query())
            ->from(['x' => new \yii\db\Expression("($sql)")])
            ->params($params)
            ->exists();

        if ($exists) {
            $this->addError($attribute, Yii::t(
                'models',
                'La tarifa seleccionada se superpone con otra tarifa ya asociada a esta cabaña.'
            ));
        }
            */
    }


    public static function isTarifaRangeOverlap($id_cabana, $id_tarifa)
    {


        if (!$id_cabana || !$id_tarifa) {
            return [
                'status' => 'error',
                'msg' => Yii::t(
                    'models',
                    'No existe la cabaña o la tarifa.'
                )
            ];
        }

        // Obtener la tarifa seleccionada y su rango
        $tarifa = \app\models\Tarifa::findOne($id_tarifa);
        if (!$tarifa || empty($tarifa->inicio) || empty($tarifa->fin)) {

            return [
                'status' => 'error',
                'msg' => Yii::t(
                    'models',
                    'La tarifa seleccionada no tiene un rango válido.'
                )
            ];

        }

        $newInicio = $tarifa->inicio; // asume 'Y-m-d' o 'Y-m-d H:i:s' según tu BD
        $newFin = $tarifa->fin;

        // Buscar cualquier vínculo existente de la misma cabaña cuyo rango se superponga
        $params = [
            ':cabana' => $id_cabana,
            ':new_inicio' => $newInicio,
            ':new_fin' => $newFin,
        ];

        $sql = "
                SELECT 1
                FROM cabanas_tarifas ct
                INNER JOIN tarifas t ON t.id = ct.id_tarifa
                WHERE ct.id_cabana = :cabana
                AND NOT (
                        :new_fin   < t.inicio
                    OR  :new_inicio > t.fin
                )
                LIMIT 1
            ";


        $exists = (new \yii\db\Query())
            ->from(['x' => new \yii\db\Expression("($sql)")])
            ->params($params)
            ->exists();

        if ($exists) {

            return [
                'status' => 'SI',
                'msg' => Yii::t(
                    'models',
                    'La tarifa seleccionada se superpone con otra tarifa ya asociada a esta cabaña.'
                )
            ];

        }

        return [
            'status' => 'NO',
            'msg' => Yii::t(
                'models',
                'La tarifa seleccionada no se superpone con otra tarifa ya asociada a esta cabaña.'
            )
        ];

    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'id_cabana' => Yii::t('models', 'Cabaña'),
            'id_tarifa' => Yii::t('models', 'Tarifa'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }


    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'id' => Yii::t('models', 'ID'),
            'id_cabana' => Yii::t('models', 'Seleccione la Cabaña'),
            'id_tarifa' => Yii::t('models', 'Seleccione la Tarifa a asociar'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCabana()
    {
        return $this->hasOne(\app\models\Cabana::class, ['id' => 'id_cabana']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTarifa()
    {
        return $this->hasOne(\app\models\Tarifa::class, ['id' => 'id_tarifa']);
    }

}
