<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "cabanas".
 *
 * @property integer $id
 * @property string $descr
 * @property string $checkin
 * @property string $checkout
 * @property integer $max_pax
 * @property integer $activa
 * @property array $caracteristicas
 * @property array $config
 * @property integer $numero
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\CabanaTarifa[] $cabanasTarifas
 * @property \app\models\RequestCabana[] $requestCabanas
 * @property \app\models\RequestReserva[] $requests
 * @property \app\models\ReservaCabana[] $reservaCabanas
 * @property \app\models\Reserva[] $reservas
 * @property \app\models\Tarifa[] $tarifas
 */
abstract class Cabana extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cabanas';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();

        return ArrayHelper::merge($parentRules, [
            [['descr', 'checkin', 'checkout', 'max_pax', 'activa', 'numero'], 'required'],

            // checkin / checkout como hora (HH:mm)
            [['checkin', 'checkout'], 'date', 'type' => 'time', 'format' => 'php:H:i'],

            // checkin > checkout
            ['checkin', 'validateCheckinAfterCheckout'],

            // max_pax entre 1 y 9
            ['max_pax', 'integer', 'min' => 1, 'max' => 9],

            ['numero', 'integer', 'min' => 1, 'max' => 99],

            // activa solo 0 o 1
            //['activa', 'in', 'range' => [0, 1], 'strict' => true],
            ['activa', 'boolean'],

            [['caracteristicas', 'config'], 'safe'],
            [['descr'], 'string', 'max' => 45],
            [['descr'], 'unique'],
            [['numero'], 'unique'],
        ]);
    }

    /**
     * Valida que checkin sea posterior a checkout (HH:mm).
     */
    public function validateCheckinAfterCheckout($attribute, $params = [])
    {
        if (empty($this->$attribute) || empty($this->checkout)) {
            return;
        }

        $in = \DateTime::createFromFormat('H:i', $this->$attribute);
        $out = \DateTime::createFromFormat('H:i', $this->checkout);

        if (!$in || !$out) {
            return; // el validador 'date' se encarga si el formato no es válido
        }

        if ($in <= $out) {
            $this->addError($attribute, Yii::t(
                'models',
                'La hora de ingreso debe ser posterior a la hora de egreso.'
            ));
        }
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'descr' => Yii::t('models', 'Denominacion'),
            'checkin' => Yii::t('models', 'Hora del Ingreso'),
            'checkout' => Yii::t('models', 'Hora del egreso'),
            'max_pax' => Yii::t('models', 'Capacidad Maxima'),
            'activa' => Yii::t('models', 'Esta Activa'),
            'caracteristicas' => Yii::t('models', 'Caracteristicas'),
            'config' => Yii::t('models', 'Configuracion'),
            'numero' => Yii::t('models', 'Numero'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }


    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'id' => Yii::t('models', 'ID'),
            'descr' => Yii::t('models', 'Ingrese el nombre de la cabana (no debe estar utilizado)'),
            'checkin' => Yii::t('models', 'Indique la Hora del Ingreso (debe ser menor a la de egreso)'),
            'checkout' => Yii::t('models', 'Indique la Hora del Egreso (debe ser mayor a la de ingreso)'),
            'max_pax' => Yii::t('models', 'Indique la Capacidad Maxima de pasajeros'),
            'activa' => Yii::t('models', 'Indique si esta activa o no '),
            'caracteristicas' => Yii::t('models', 'Ingrese las Caracteristicas'),
            'numero' => Yii::t('models', 'Ingrese el Numero de la Cabana'),
            'config' => Yii::t('models', 'Ingrese las configuraciones'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCabanasTarifas()
    {
        return $this->hasMany(\app\models\CabanaTarifa::class, ['id_cabana' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestCabanas()
    {
        return $this->hasMany(\app\models\RequestCabana::class, ['id_cabana' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequests()
    {
        return $this->hasMany(\app\models\RequestReserva::class, ['id' => 'id_request'])->viaTable('request_cabanas', ['id_cabana' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservaCabanas()
    {
        return $this->hasMany(\app\models\ReservaCabana::class, ['id_cabana' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservas()
    {
        return $this->hasMany(\app\models\Reserva::class, ['id' => 'id_reserva'])->viaTable('reserva_cabanas', ['id_cabana' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTarifas()
    {
        return $this->hasMany(\app\models\Tarifa::class, ['id' => 'id_tarifa'])->viaTable('cabanas_tarifas', ['id_cabana' => 'id']);
    }

}
