<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "estados".
 *
 * @property integer $id
 * @property string $descr
 * @property string $slug
 *
 * @property \app\models\RequestReservas[] $requestReservas
 * @property \app\models\Reservas[] $reservas
 */
abstract class Estado extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'estados';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['descr', 'slug'], 'required'],
            [['descr', 'slug'], 'string', 'max' => 45],
            [['descr'], 'unique'],
            [['slug'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'descr' => Yii::t('models', 'Descr'),
            'slug' => Yii::t('models', 'Slug'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestReservas()
    {
        return $this->hasMany(\app\models\RequestReservas::class, ['id_estado' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservas()
    {
        return $this->hasMany(\app\models\Reservas::class, ['id_estado' => 'id']);
    }

}
