<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "locadores".
 *
 * @property integer $id
 * @property string $denominacion
 * @property string $documento
 * @property string $email
 * @property string $telefono
 * @property string $domicilio
 * @property array $documentos
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Reserva[] $reservas
 */
abstract class Locador extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'locadores';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['denominacion', 'documento', 'email', 'telefono'], 'required'],
            [['documentos'], 'safe'],
            [['denominacion', 'domicilio'], 'string', 'max' => 100],
            [['documento', 'email', 'telefono'], 'string', 'max' => 45],
            [['documento'], 'unique'],
            [['email'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'denominacion' => Yii::t('models', 'Denominacion'),
            'documento' => Yii::t('models', 'Documento'),
            'email' => Yii::t('models', 'Email'),
            'telefono' => Yii::t('models', 'Telefono'),
            'domicilio' => Yii::t('models', 'Domicilio'),
            'documentos' => Yii::t('models', 'Documentos'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservas()
    {
        return $this->hasMany(\app\models\Reserva::class, ['id_locador' => 'id']);
    }

}
