<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "request_responses".
 *
 * @property integer $id
 * @property integer $id_request
 * @property string $fecha
 * @property string $response
 * @property integer $is_response
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\RequestReserva $request
 */
abstract class RequestResponse extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'request_responses';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['id_request', 'fecha', 'response'], 'required'],
            [['id_request', 'is_response'], 'integer'],
            [['fecha', 'is_response'], 'safe'],
            [['response'], 'string', 'max' => 500],
            [['id_request'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\RequestReserva::class, 'targetAttribute' => ['id_request' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'id_request' => Yii::t('models', 'Solicitud'),
            'fecha' => Yii::t('models', 'Creado'),
            'response' => Yii::t('models', 'Mensaje'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }


    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'id' => Yii::t('models', 'ID'),
            'id_request' => Yii::t('models', 'Solicitud'),
            'fecha' => Yii::t('models', 'Creado'),
            'response' => Yii::t('models', 'Ingrese el mensaje'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequest()
    {
        return $this->hasOne(\app\models\RequestReserva::class, ['id' => 'id_request']);
    }

}
