<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "request_reservas".
 *
 * @property integer $id
 * @property string $fecha
 * @property string $desde
 * @property string $hasta
 * @property string $denominacion
 * @property string $email
 * @property integer $pax
 * @property string $hash
 * @property double $total
 * @property integer $id_estado
 * @property integer $id_reserva
 * @property string $obs
 * @property string $fecha_request_pago
 * @property array $registro_pagos
 * @property double $pagado
 * @property string $email_token
 * @property string $email_token_expira
 * @property string $codigo_reserva 
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Cabana[] $cabanas
 * @property \app\models\Estado $estado
 * @property \app\models\RequestCabana[] $requestCabanas
 * @property \app\models\RequestResponse[] $requestResponses
 * @property \app\models\Reserva $reserva
 */
abstract class RequestReserva extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'request_reservas';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['fecha', 'desde', 'hasta', 'denominacion', 'email', 'pax', 'hash', 'total', 'id_estado'], 'required'],
            [['fecha', 'desde', 'hasta', 'fecha_request_pago', 'registro_pagos', 'email_token', 'email_token_expira'], 'safe'],
            [['pax', 'id_estado', 'id_reserva'], 'integer'],
            [['total', 'pagado'], 'number'],
            [['obs'], 'string', 'max' => 500],
            [['denominacion'], 'string', 'max' => 100],
            [['email', 'hash', 'codigo_reserva'], 'string', 'max' => 45],
            [['id_reserva'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Reserva::class, 'targetAttribute' => ['id_reserva' => 'id']],
            [['id_estado'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Estado::class, 'targetAttribute' => ['id_estado' => 'id']],
            [['email', 'codigo_reserva'], 'unique', 'targetAttribute' => ['email', 'codigo_reserva']],
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'fecha' => Yii::t('models', 'Creada'),
            'desde' => Yii::t('models', 'Desde'),
            'hasta' => Yii::t('models', 'Hasta'),
            'denominacion' => Yii::t('models', 'Cliente'),
            'email' => Yii::t('models', 'Email'),
            'pax' => Yii::t('models', 'Pasajeros'),
            'hash' => Yii::t('models', 'Hash'),
            'total' => Yii::t('models', 'Total'),
            'id_estado' => Yii::t('models', 'Estado'),
            'id_reserva' => Yii::t('models', 'Reserva'),
            'obs' => Yii::t('models', 'Obs'),
            'fecha_request_pago' => Yii::t('models', 'Fecha Request Pago'),
            'registro_pagos' => Yii::t('models', 'Registro Pagos'),
            'codigo_reserva' => Yii::t('models', 'Codigo Reserva'),
            'pagado' => Yii::t('models', 'Pagado'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCabanas()
    {
        return $this->hasMany(\app\models\Cabana::class, ['id' => 'id_cabana'])->viaTable('request_cabanas', ['id_request' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(\app\models\Estado::class, ['id' => 'id_estado']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestCabanas()
    {
        return $this->hasMany(\app\models\RequestCabana::class, ['id_request' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestResponses()
    {
        return $this->hasMany(\app\models\RequestResponse::class, ['id_request' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReserva()
    {
        return $this->hasOne(\app\models\Reserva::class, ['id' => 'id_reserva']);
    }

}
