<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "reserva_cabanas".
 *
 * @property integer $id
 * @property integer $id_cabana
 * @property integer $id_reserva
 * @property double $valor
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Cabana $cabana
 * @property \app\models\Reserva $reserva
 */
abstract class ReservaCabana extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reserva_cabanas';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['id_cabana', 'id_reserva', 'valor'], 'required'],
            [['id_cabana', 'id_reserva'], 'integer'],
            [['valor'], 'number'],
            [['id_cabana', 'id_reserva'], 'unique', 'targetAttribute' => ['id_cabana', 'id_reserva']],
            [['id_cabana'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Cabana::class, 'targetAttribute' => ['id_cabana' => 'id']],
            [['id_reserva'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Reserva::class, 'targetAttribute' => ['id_reserva' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'id_cabana' => Yii::t('models', 'Cabana'),
            'id_reserva' => Yii::t('models', 'Reserva'),
            'valor' => Yii::t('models', 'Valor total'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCabana()
    {
        return $this->hasOne(\app\models\Cabana::class, ['id' => 'id_cabana']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReserva()
    {
        return $this->hasOne(\app\models\Reserva::class, ['id' => 'id_reserva']);
    }

}
