<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "reservas".
 *
 * @property integer $id
 * @property string $fecha
 * @property string $desde
 * @property string $hasta
 * @property integer $id_locador
 * @property integer $pax
 * @property integer $id_estado
 * @property string $obs
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Cabana[] $cabanas
 * @property \app\models\Estado $estado
 * @property \app\models\Locador $locador
 * @property \app\models\RequestReserva[] $requestReservas
 * @property \app\models\ReservaCabana[] $reservaCabanas
 */
abstract class Reserva extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reservas';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['fecha', 'desde', 'hasta', 'id_locador', 'pax', 'id_estado'], 'required'],
            [['fecha', 'desde', 'hasta'], 'safe'],
            [['id_locador', 'pax', 'id_estado'], 'integer'],

            // Validación: pax > 0
            ['pax', 'integer', 'min' => 1, 'tooSmall' => Yii::t('models', 'La cantidad de pasajeros debe ser mayor a 0.')],

            // Validación: obs máx 500 caracteres
            ['obs', 'string', 'max' => 500, 'tooLong' => Yii::t('models', 'La nota no puede superar los 500 caracteres.')],

            // Validación: desde <= hasta
            ['desde', 'validateFechaRango'],

            [['id_estado'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Estado::class, 'targetAttribute' => ['id_estado' => 'id']],
            [['id_locador'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Locador::class, 'targetAttribute' => ['id_locador' => 'id']]
        ]);
    }


    /**
     * Valida que la fecha 'desde' sea menor o igual que 'hasta'
     */
    public function validateFechaRango($attribute, $params = [])
    {
        if (empty($this->desde) || empty($this->hasta)) {
            return;
        }

        $inicio = \DateTime::createFromFormat('Y-m-d', $this->desde);
        $fin = \DateTime::createFromFormat('Y-m-d', $this->hasta);

        if (!$inicio || !$fin) {
            // si las fechas no son válidas, se ignora (lo marcará el validador 'date' si existiera)
            return;
        }

        if ($inicio > $fin) {
            $this->addError($attribute, Yii::t('models', 'La fecha de inicio debe ser menor o igual que la fecha de salida.'));
        }
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'fecha' => Yii::t('models', 'Creada'),
            'desde' => Yii::t('models', 'Desde'),
            'hasta' => Yii::t('models', 'Hasta'),
            'id_locador' => Yii::t('models', 'Pasajero'),
            'pax' => Yii::t('models', 'Cantidad de pasajeros'),
            'id_estado' => Yii::t('models', 'Estado'),
            'obs' => Yii::t('models', 'Notas'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'id' => Yii::t('models', 'ID'),
            'fecha' => Yii::t('models', 'Creada'),
            'desde' => Yii::t('models', 'Desde'),
            'hasta' => Yii::t('models', 'Hasta'),
            'id_locador' => Yii::t('models', 'Pasajero'),
            'pax' => Yii::t('models', 'Cantidad de pasajeros'),
            'id_estado' => Yii::t('models', 'Estado'),
            'obs' => Yii::t('models', 'Notas'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCabanas()
    {
        return $this->hasMany(\app\models\Cabana::class, ['id' => 'id_cabana'])->viaTable('reserva_cabanas', ['id_reserva' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(\app\models\Estado::class, ['id' => 'id_estado']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocador()
    {
        return $this->hasOne(\app\models\Locador::class, ['id' => 'id_locador']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestReservas()
    {
        return $this->hasMany(\app\models\RequestReserva::class, ['id_reserva' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReservaCabanas()
    {
        return $this->hasMany(\app\models\ReservaCabana::class, ['id_reserva' => 'id']);
    }

}
