<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "tarifas".
 *
 * @property integer $id
 * @property string $fecha
 * @property string $descr
 * @property string $inicio
 * @property string $fin
 * @property double $valor_dia
 * @property integer $min_dias
 * @property integer $activa
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Cabana[] $cabanas
 * @property \app\models\CabanaTarifa[] $cabanasTarifas
 */
abstract class Tarifa extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tarifas';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['blameable'] = [
            'class' => BlameableBehavior::class,
        ];
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
        ];

        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parent = parent::rules();

        return ArrayHelper::merge($parent, [
            // o seteala por defecto (ver más abajo)
            [['descr', 'inicio', 'fin', 'valor_dia', 'min_dias', 'activa', 'fecha'], 'required'],

            // --- Normalización de fechas ---
            // inicio: acepta "YYYY-MM-DD" o "YYYY-MM-DDTHH:mm" y lo pasa a "YYYY-MM-DD HH:MM:SS"
            [
                'inicio',
                'filter',
                'filter' => function ($v) {
                    if ($v === null || $v === '')
                        return $v;
                    $v = trim(str_replace('T', ' ', $v));       // 2025-11-07T15:30 -> 2025-11-07 15:30
                    if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $v)) {
                        // solo fecha -> comienzo del día
                        return $v . ' 00:00:00';
                    }
                    if (preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/', $v)) {
                        return $v . ':00';
                    }
                    return $v;
                }
            ],
            // fin: idem, pero fin del día si viene solo fecha
            [
                'fin',
                'filter',
                'filter' => function ($v) {
                    if ($v === null || $v === '')
                        return $v;
                    $v = trim(str_replace('T', ' ', $v));
                    if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $v)) {
                        return $v . ' 23:59:59';
                    }
                    if (preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/', $v)) {
                        return $v . ':00';
                    }
                    return $v;
                }
            ],

            // Validar como DATETIME luego de normalizar
            [['inicio', 'fin'], 'date', 'type' => 'datetime', 'format' => 'php:Y-m-d H:i:s'],

            // inicio < fin
            ['inicio', 'validateInicioBeforeFin'],

            // > 0
            ['min_dias', 'integer', 'min' => 1],
            ['valor_dia', 'number', 'min' => 0.000001],

            ['fecha', 'default', 'value' => function () {
                return date('Y-m-d H:i:s'); }],
            ['fecha', 'date', 'type' => 'datetime', 'format' => 'php:Y-m-d H:i:s', 'skipOnEmpty' => true],

            [['activa', 'created_by', 'updated_by'], 'integer'],
            [['descr'], 'string', 'max' => 45],
            [['descr'], 'unique'],
            [['created_at', 'updated_at'], 'safe'],
        ]);
    }


    /**
     * Valida que inicio sea estrictamente menor a fin (ambos en 'Y-m-d H:i:s').
     */
    public function validateInicioBeforeFin($attribute, $params = [])
    {
        if (empty($this->inicio) || empty($this->fin))
            return;

        $ini = \DateTime::createFromFormat('Y-m-d H:i:s', $this->inicio);
        $end = \DateTime::createFromFormat('Y-m-d H:i:s', $this->fin);

        if (!$ini || !$end)
            return; // deja que el validador 'date' marque error

        if ($ini >= $end) {
            $this->addError($attribute, Yii::t(
                'models',
                'La fecha de inicio debe ser menor que la fecha de fin.'
            ));
        }
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'fecha' => Yii::t('models', 'Creada'),
            'descr' => Yii::t('models', 'Descripcion'),
            'inicio' => Yii::t('models', 'Inicio'),
            'fin' => Yii::t('models', 'Fin'),
            'valor_dia' => Yii::t('models', 'Valor del Dia'),
            'min_dias' => Yii::t('models', 'Min. Dias'),
            'activa' => Yii::t('models', 'Es Activa'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }


    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'id' => Yii::t('models', 'ID'),
            'fecha' => Yii::t('models', 'Fecha'),
            'descr' => Yii::t('models', 'Ingrese la Descripcion: (no debe estar utilizado)'),
            'inicio' => Yii::t('models', 'Indique la fecha de Inicio de la Tarifa'),
            'fin' => Yii::t('models', 'Indique la fecha de Fin de la Tarifa'),
            'valor_dia' => Yii::t('models', 'Indique el Valor del Dia'),
            'min_dias' => Yii::t('models', 'Indique el Min. Dias de Reserva para aplicar la Tarifa'),
            'activa' => Yii::t('models', 'Indique si esta Activa'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCabanas()
    {
        return $this->hasMany(\app\models\Cabana::class, ['id' => 'id_cabana'])->viaTable('cabanas_tarifas', ['id_tarifa' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCabanasTarifas()
    {
        return $this->hasMany(\app\models\CabanaTarifa::class, ['id_tarifa' => 'id']);
    }


}
